### ISSUE TITLE
dlib_to_sfm.txt

### ISSUE THREAD

**Issue by virtualenv** [JerryWu96/3D_Face_Reconstrction#1]
Hello,

I am looking for the dlib_to_sfm.txt file.
Could you kindly tell me where can I find it ?

Thank you!

**Comment by JerryWu96** [comment]
> Hello,
> 
> I am looking for the dlib_to_sfm.txt file.
> Could you kindly tell me where can I find it ?
> 
> Thank you!

Unfortunately this file has been removed due to the fact that the original format of Surrey Face Model is no longer being supported by University of Surrey lab. 

Please go to https://www.cvssp.org/faceweb/3dmm/facemodel/ and ask for the latest format & parser they provide, so that you can work on your new dlib-to-sfm mapper file.

**Comment by virtualenv** [comment]
Dear JerryWu96,

Thank you for the super fast reply!
Okay, I will ask them.
Meanwhile, thank you so much for sharing this amazing project!

All the best!
