### ISSUE TITLE
Hi, JerryWu, I tried to run your 3D

### ISSUE THREAD

**Issue by Jared-Dai** [JerryWu96/3D_Face_Reconstrction#2]

**Comment by Jared-Dai** [comment]
![微信截图_20200618155028](https://user-images.githubusercontent.com/66655052/84993286-ac6ade00-b17b-11ea-881b-e24468e75444.png)
I found this file is lacked, Could you plz tell me how to get this file

**Comment by JerryWu96** [comment]
Sorry that I did not receive a notification on this issue. Hope it is not too late!
This file was deprecated because right now Surrey Face Models are in a new format as well as new python code to handle. This mapping was initially created to map the landmarks from dlib to a really old version of sfm model file, which no longer works. 

Please check with the official SFM model website and I believe a new mapping approach should be created based on your needs.
