### ISSUE TITLE
Texture extraction

### ISSUE THREAD

**Issue by dosomder** [JerryWu96/3D_Face_Reconstrction#3]
Hi @JerryWu96 

I am intersted in the part that extracts a texture based on the facial landmark points. Could you point me to the code which is responsible for that? It's a bit hard to understand since the comments are in Chinese.

Is the morphable face model needed for this part?

**Comment by JerryWu96** [comment]
Hi dosomder,

I believe it is at line 216 in Reconstruct.cpp. Meanwhile, since this project has been relatively old and my laptop has been replaced, there is a file that is missing in the repo: dlib_to_sfm.txt, which I manually created to make the system work. I will take a look at my external hard drives and hope that I have a backup for it.

Sorry that the comments issues, I wasn't fluent in English back then and I did not realize that dozens of people had trouble reading the code. This was a small side-project that I only spent a week working on, so I did not spend time refining it. Actually it was just for fun, so I did not pay attention to code quality. Perhaps I will update them in English if possible.
